// Bundles the game (and three.js) into ONE self-contained index.html that
// works by double-clicking it - no server or internet needed (fonts are
// optional and fall back to system fonts offline).
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'fs';

const result = await build({
  entryPoints: ['src/main.js'],
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['chrome100', 'edge100', 'firefox100'],
  write: false,
  legalComments: 'none',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const css = readFileSync('src/style.css', 'utf8');
let html = readFileSync('src/index.html', 'utf8');
html = html.replace(/<!--BUILD:CSS-->[\s\S]*?<!--\/BUILD:CSS-->/, () => `<style>\n${css}</style>`);
html = html.replace(/<!--BUILD:JS-->[\s\S]*?<!--\/BUILD:JS-->/, () => `<script>\n${js}</script>`);
html = html.replace('<head>', '<head>\n<!-- Generated by build.mjs from src/ - edit the sources, then run: npm run build -->');
writeFileSync('index.html', html);
console.log(`index.html written (${(html.length / 1024).toFixed(0)} KB)`);
